"""Created user table

Revision ID: 472cb2e264bc
Revises: 7c102e936fe1
Create Date: 2026-09-16 17:47:43.465093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472cb2e264bc'
down_revision: Union[str, Sequence[str], None] = '7c102e936fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('users',
  sa.Column('uid', sa.String(length=6), nullable=False),
  sa.Column('created', sa.DateTime(), nullable=False),
  sa.Column('updated', sa.DateTime(), nullable=False),
  sa.PrimaryKeyConstraint('uid')
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('users')
  # ### end Alembic commands ###
