"""Database creation

Revision ID: 4756f3345db0
Revises: 4803ba755674
Create Date: 2026-04-28 14:23:48.834144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4756f3345db0'
down_revision: Union[str, Sequence[str], None] = '4803ba755674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('domains',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('name', sa.String(length=255), nullable=False),
  sa.Column('type', sa.Enum('HOSTNAME', 'PORT_PROXY', name='domaintype', native_enum=False), nullable=False),
  sa.Column('enabled', sa.Boolean(), nullable=False),
  sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DISABLED', 'ERROR', name='domainstatus', native_enum=False), nullable=False),
  sa.Column('created', sa.DateTime(), nullable=False),
  sa.Column('updated', sa.DateTime(), nullable=False),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('name')
  )
  op.create_table('domain_certificates',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('domain_id', sa.Integer(), nullable=False),
  sa.Column('provider', sa.String(length=64), nullable=False),
  sa.Column('cert_name', sa.String(length=255), nullable=False),
  sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'REVOKED', 'ERROR', name='certificatestatus', native_enum=False), nullable=False),
  sa.Column('issued_at', sa.DateTime(), nullable=True),
  sa.Column('expires_at', sa.DateTime(), nullable=True),
  sa.Column('last_renewal_attempt_at', sa.DateTime(), nullable=True),
  sa.Column('fullchain_path', sa.Text(), nullable=True),
  sa.Column('private_key_path', sa.Text(), nullable=True),
  sa.Column('last_error', sa.Text(), nullable=True),
  sa.Column('created', sa.DateTime(), nullable=False),
  sa.Column('updated', sa.DateTime(), nullable=False),
  sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index('ix_domain_certificates_domain_status', 'domain_certificates', ['domain_id', 'status'], unique=False)
  op.create_index('ix_domain_certificates_expires_at', 'domain_certificates', ['expires_at'], unique=False)
  op.create_table('domain_deployments',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('domain_id', sa.Integer(), nullable=False),
  sa.Column('status', sa.Enum('DRAFT', 'APPLIED', 'ERROR', name='deploymentstatus', native_enum=False), nullable=False),
  sa.Column('nginx_filename', sa.String(length=255), nullable=False),
  sa.Column('sites_available_path', sa.Text(), nullable=False),
  sa.Column('sites_enabled_path', sa.Text(), nullable=False),
  sa.Column('config_text', sa.Text(), nullable=False),
  sa.Column('applied_at', sa.DateTime(), nullable=True),
  sa.Column('last_error', sa.Text(), nullable=True),
  sa.Column('created', sa.DateTime(), nullable=False),
  sa.Column('updated', sa.DateTime(), nullable=False),
  sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index('ix_domain_deployments_domain_status', 'domain_deployments', ['domain_id', 'status'], unique=False)
  op.create_table('domain_routes',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('domain_id', sa.Integer(), nullable=False),
  sa.Column('upstream_host', sa.String(length=255), nullable=False),
  sa.Column('upstream_port', sa.Integer(), nullable=False),
  sa.Column('upstream_scheme', sa.Enum('HTTP', 'HTTPS', 'STREAM', name='upstreamscheme', native_enum=False), nullable=False),
  sa.Column('listen_port', sa.Integer(), nullable=True),
  sa.Column('stream_protocol', sa.Enum('TCP', 'UDP', name='streamprotocol', native_enum=False), nullable=False),
  sa.Column('created', sa.DateTime(), nullable=False),
  sa.Column('updated', sa.DateTime(), nullable=False),
  sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('domain_id')
  )
  op.create_table('domain_server_names',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('domain_id', sa.Integer(), nullable=False),
  sa.Column('name', sa.String(length=255), nullable=False),
  sa.Column('is_primary', sa.Boolean(), nullable=False),
  sa.Column('created', sa.DateTime(), nullable=False),
  sa.Column('updated', sa.DateTime(), nullable=False),
  sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('domain_id', 'name', name='uq_domain_server_names_domain_name')
  )
  op.create_index('ix_domain_server_names_name', 'domain_server_names', ['name'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index('ix_domain_server_names_name', table_name='domain_server_names')
  op.drop_table('domain_server_names')
  op.drop_table('domain_routes')
  op.drop_index('ix_domain_deployments_domain_status', table_name='domain_deployments')
  op.drop_table('domain_deployments')
  op.drop_index('ix_domain_certificates_expires_at', table_name='domain_certificates')
  op.drop_index('ix_domain_certificates_domain_status', table_name='domain_certificates')
  op.drop_table('domain_certificates')
  op.drop_table('domains')
  # ### end Alembic commands ###
